name: dieta_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  
  flutter: 
    sdk: flutter
  flutter_vector_icons: ^2.0.0
  get_storage: ^2.1.1
  get: 4.6.5
  group_button: ^5.3.2
  validatorless: ^1.2.3

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/em-forma-man.png
    - assets/images/em-forma-woman.png
    - assets/icons/cooking-stove.png
    - assets/icons/cooking.png
    - assets/icons/form.png
    - assets/icons/food-serving.png


