name: dieta_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.1
  
  flutter: 
    sdk: flutter
  flutter_vector_icons: ^2.0.0
  get_storage: ^2.1.1
  get: 4.6.5
  google_fonts: ^3.0.1
  group_button: ^5.3.2
  image_picker: 1.0.4
  permission_handler: 11.0.1
  phosphor_flutter: ^1.0.0
  validatorless: ^1.2.4
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/em-forma-man.png
    - assets/images/em-forma-woman.png
    - assets/icons/cooking-stove.png
    - assets/icons/cooking.png
    - assets/icons/form.png
    - assets/icons/food-serving.png
  
  # fonts:
  #   - family: Gilmer
  #     fonts:
  #       - asset: assets/fonts/Gilmer-Font/Gilmer Regular.otf
  #   - family: GilmerMedium
  #     fonts:
  #       - asset: assets/fonts/Gilmer-Font/Gilmer Medium.otf

  #   - family: GilmerLight
  #     fonts:
  #       - asset: assets/fonts/Gilmer-Font/Gilmer Light.otf

  #   - family: GilmerHeavy
  #     fonts:
  #       - asset: assets/fonts/Gilmer-Font/Gilmer Heavy.otf

  #   - family: GilmerBold
  #     fonts:
  #       - asset: assets/fonts/Gilmer-Font/Gilmer Bold.otf
          


