import 'package:dieta_mobile/app/data/models/alimento_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class RefeicaoModel {
/*
{
  "descricao": "nome",
  "proteinas": 1,
  "carboidratos": 2.3,
  "gorduras": 2.3,
  "calorias": 5.2,
  "alimentos": [
    {
      "descricao": "nome",
      "proteinas": 1,
      "carboidratos": 2.3,
      "gorduras": 2.3,
      "calorias": 5.2
    }
  ]
} 
*/

  String? descricao;
  double? proteinas;
  double? carboidratos;
  double? gorduras;
  double? calorias;
  List<AlimentoModel?>? alimentos;

  RefeicaoModel({
    this.descricao,
    this.proteinas,
    this.carboidratos,
    this.gorduras,
    this.calorias,
    this.alimentos,
  });
  RefeicaoModel.fromJson(Map<String, dynamic> json) {
    descricao = json['descricao']?.toString();
    proteinas = json['proteinas']?.toInt();
    carboidratos = json['carboidratos']?.toDouble();
    gorduras = json['gorduras']?.toDouble();
    calorias = json['calorias']?.toDouble();
    if (json['alimentos'] != null) {
      final v = json['alimentos'];
      final arr0 = <AlimentoModel>[];
      v.forEach((v) {
        arr0.add(AlimentoModel.fromJson(v));
      });
      alimentos = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['descricao'] = descricao;
    data['proteinas'] = proteinas;
    data['carboidratos'] = carboidratos;
    data['gorduras'] = gorduras;
    data['calorias'] = calorias;
    if (alimentos != null) {
      final v = alimentos;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['alimentos'] = arr0;
    }
    return data;
  }

  double totalProteinas() {
    double result = 0.0;
    if (alimentos != null) {
      for (var element in alimentos!) {
        if (element!.proteinas != null) {
          result = result + element.proteinas!;
        }
      }
    }

    return result;
  }
}
