///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserModel {
/*
{
  "genero": "",
  "GDA": 1,
  "peso": 2.3,
  "altura": "hello",
  "idade": "hello",
  "FA": "hello"
} 
*/

  String? genero;
  int? gda;
  double? peso;
  String? altura;
  String? idade;
  String? fa;

  UserModel({
    this.genero,
    this.gda,
    this.peso,
    this.altura,
    this.idade,
    this.fa,
  });
  UserModel.fromJson(Map<String, dynamic> json) {
    genero = json['genero']?.toString();
    gda = json['gda']?.toInt();
    peso = json['peso']?.toDouble();
    altura = json['altura']?.toString();
    idade = json['idade']?.toString();
    fa = json['fa']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['genero'] = genero;
    data['gda'] = gda;
    data['peso'] = peso;
    data['altura'] = altura;
    data['idade'] = idade;
    data['fa'] = fa;
    return data;
  }
}
